### PR TITLE
Added some image galleries

### PR DESCRIPTION
**Pull request by alchzh**
Hey dude, is it okay to resize those images? They're a little big

### CODE REVIEW

**Comment by frogocomics** [comment]
What is the purpose of images.md, and is it possible to display the images on the md file? When I open the md file, all I see are some links to the images.

**Comment by frogocomics** [comment]
Is it possible to change the behavior?

**Comment by frogocomics** [comment]
Thank you for your contribution. How could I credit you?

**Comment by alchzh** [comment]
Err... Make me contributor and just add acz13 somewhere :smile:

**Pull request merged**
