### PR TITLE
README Changes

### PR DESCRIPTION
**Pull request by alchzh**
For the unadvised...

### CODE REVIEW

**Comment by frogocomics** [comment]
Could you please make a contributor list?

**Comment by frogocomics** [comment]
Also, you have been given pull access, but if you pull before you add a contribution list, I won't be happy! xD

**Comment by alchzh** [comment]
Gee thanks for push privs. Should I merge this PR?

**Comment by frogocomics** [comment]
Make a contributor list first please.

**Comment by alchzh** [comment]
I just did

**Comment by frogocomics** [comment]
Merge.

**Pull request merged**
