### PR TITLE
Added files via upload

### PR DESCRIPTION
**Pull request by wunder-bread**
Added Picea Mariana & imgs. Added bo2 files for all current .schematics

### CODE REVIEW

**Comment by frogocomics** [comment]
Thank you for the commit! There are some things that should be change though. **A L2 and S2 schematic should be added (This is for variation!)**, and  the images should be removed now that I seen them. Why is this so? I am planning to make a render for them as soon as this is accepted. Thanks!

**Comment by alchzh** [comment]
Hey wunder-bread! I'm not frogocomics, so take that for what you will. Can you move the schematics to to Schematics folder and rename bo2's to simply bo2s? Dirs with apostrophes are annoying. You might want to take individual screenshots of the trees rather than whole to work with `images.md` and `genimages.py`

Edit: O dang same time :smile:

**Comment by frogocomics** [comment]
Acz13 no screenshots: I will make renders!

**Comment by alchzh** [comment]
@wunder-bread welcome to github!

@frogocomics can I have contrib privs? PRing is kind of annoying for the scripts :question:

**Comment by frogocomics** [comment]
Also, The sapling version should instead be XS, and a variant should be made for that also!

**Comment by acz13** [comment]
Also: thanks for the biome files. You might want to consider that multiple types of trees (like dogwood) live in the same environment.

**Comment by acz13** [comment]
@wunder-bread why not BO3 instead of BO2?

**Comment by wunder-bread** [comment]
Making the changes now. Sorry if I'm messing this up. First time working with github. And how do you get those white bases on your renders?

**Comment by frogocomics** [comment]
I will do the renders, they are made in cinema4d

**Comment by frogocomics** [comment]
Also, could you rename your files from Picea Mariana to Pircea mariana? Thank you for your contributions by the way :D

**Comment by wunder-bread** [comment]
No problem. Was just curious about the renders because I just got 4D, and was wondering how to do that.

**Comment by frogocomics** [comment]
Oh? Simple: make a really big plane, then create a Nukei shader to it, then add a physical sky.

**Comment by alchzh** [comment]
IMO just use chunky :D  
@wunder-bread to edit the PR change [your fork](https://github.com/wunder-bread/OpenTrees) and it'll update here

**Comment by frogocomics** [comment]
Your changes were made.

**Pull request closed without merging**
